name: FUNCTIONS_PYTHON_GH_ACTION

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: 'Run pip'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for pip in pushd
        pushd .
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/python3.6/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: demo0x1234
        package: '.'
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}

# For more information on Github Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actionss
